---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: k8s
  become: yes
  tasks: 
  - name: create a namespace
    k8s:
      name: dev 
      api_version: v1
      kind: Namespace 
      state: present 


        
    